USE MPRICING

---- TODAS AS UNIDADES FEV - MENOS BROKER
SELECT --PERIODO,
SUM(O.QUANTIDADE) 
FROM PROJETO_BI_REVITALIZA.DBO.FATO_ORCAMENTO O 
WHERE O.CENARIO = 'CENÁRIO 1' AND O.PERIODO >= '202402' AND O.VERSAO = 'ORÇADO' AND O.COD_CANAL 
NOT IN (191)  
--GROUP BY PERIODO

SELECT SUM(VL_VOLUME) FROM TB_PREVISAO_VENDA_PRODUTO WHERE CD_ZONA NOT IN (191) AND DATA_PREVISAO ='2024-05-01'
SELECT SUM(VL_VOLUME) FROM TB_PREVISAO_VENDA WHERE CD_ZONA NOT IN (191) AND DATA_PREVISAO ='2024-05-01'
SELECT SUM(VOLUME)    FROM MPRICING.DBO.VW_PREVISAO_VENDA V WHERE V.[COD. CANAL] NOT IN (191) and V.PERÍODO ='202405' AND V.CLIENTE <> 0

---- UNIDADE DE BROKER - MAI
SELECT --PERIODO, 
SUM(O.QUANTIDADE) 
FROM PROJETO_BI_REVITALIZA.DBO.FATO_ORCAMENTO O 
WHERE O.CENARIO = 'CENÁRIO 1' AND O.PERIODO >= '202405' AND O.VERSAO = 'ORÇADO' AND O.COD_CANAL IN (191)  
--GROUP BY PERIODO

SELECT SUM(VL_VOLUME) FROM TB_PREVISAO_VENDA_PRODUTO WHERE CD_ZONA IN (191) AND DATA_PREVISAO >='2024-05-01'
SELECT SUM(VL_VOLUME) FROM TB_PREVISAO_VENDA WHERE CD_ZONA IN (191) AND DATA_PREVISAO >='2024-05-01'
SELECT SUM(VOLUME)    FROM MPRICING.DBO.VW_PREVISAO_VENDA V WHERE V.[COD. CANAL] IN (191) and V.PERÍODO >='202405' AND V.CLIENTE <> 0





----- VOLTANDO BACKUP FARMA --------------
--DELETE FROM MPRICING.DBO.TB_PREVISAO_VENDA WHERE CD_ZONA = 180 AND (DATA_PREVISAO ='2024-02-01' OR DATA_PREVISAO ='2024-03-01') 
--DELETE FROM MPRICING.DBO.TB_PREVISAO_VENDA_PRODUTO WHERE CD_ZONA = 180 AND (DATA_PREVISAO ='2024-02-01' OR DATA_PREVISAO ='2024-03-01') 

--INSERT MPRICING.DBO.TB_PREVISAO_VENDA
SELECT CD_ZONA, CD_ESTABELECIMENTO, CD_CLIENTE, CD_PRODUTO, DATA_PREVISAO, VL_VOLUME, VL_VOLUME_ORIGINAL  FROM  MPRICING.DBO.TB_PREVISAO_VENDA  WHERE CD_ZONA = 180 AND (DATA_PREVISAO ='2024-02-01' OR DATA_PREVISAO ='2024-03-01')
--INSERT MPRICING.DBO.TB_PREVISAO_VENDA_PRODUTO
SELECT CD_ZONA, CD_ESTABELECIMENTO, CD_CLIENTE, CD_PRODUTO, DATA_PREVISAO, VL_VOLUME FROM  MPRICING.DBO.TB_PREVISAO_VENDA_PRODUTO  WHERE CD_ZONA = 180 AND (DATA_PREVISAO ='2024-02-01' OR DATA_PREVISAO ='2024-03-01')


----- TRATANDO UNIDADES DIFERENTES DE BROKER -----------------------------------------------

DELETE FROM MPRICING.DBO.TB_PREVISAO_VENDA WHERE CD_ZONA <> 191 AND DATA_PREVISAO >='2024-02-01'
DELETE FROM MPRICING.DBO.TB_PREVISAO_VENDA_PRODUTO WHERE CD_ZONA <> 191 AND DATA_PREVISAO >='2024-02-01'

-- INSERINDO PREVISÃO PRODUTO
INSERT INTO TB_PREVISAO_VENDA_PRODUTO
SELECT
	O.COD_CANAL AS CD_ZONA, 
	CONVERT(VARCHAR(3),REPLICATE('0', 3 - LEN(O.COD_ESTABELECIMENTO)) + RTRIM(O.COD_ESTABELECIMENTO)) AS CD_ESTABELECIMENTO,
	O.COD_CLIENTE AS CD_CLIENTE, 
	O.COD_PRODUTO AS CD_PRODUTO,
	LEFT(O.PERIODO,4)+'-'+RIGHT(O.PERIODO,2)+'-01' AS DATA_PREVISAO,
	O.QUANTIDADE  AS VL_VOLUME
FROM 
	PROJETO_BI_REVITALIZA.DBO.FATO_ORCAMENTO O 
WHERE 
	O.QUANTIDADE IS NOT NULL AND O.QUANTIDADE > 0 AND O.CENARIO = 'CENÁRIO 1' AND O.PERIODO >= '202402' AND O.VERSAO = 'ORÇADO' AND O.COD_CANAL <> 191 

-- INSERINDO PREVISÃO EV
INSERT INTO TB_PREVISAO_VENDA
SELECT
	O.COD_CANAL AS CD_ZONA, 
	CONVERT(VARCHAR(3),REPLICATE('0', 3 - LEN(O.COD_ESTABELECIMENTO)) + RTRIM(O.COD_ESTABELECIMENTO)) AS CD_ESTABELECIMENTO,
	O.COD_CLIENTE AS CD_CLIENTE, 
	O.COD_PRODUTO AS CD_PRODUTO,
	LEFT(O.PERIODO,4)+'-'+RIGHT(O.PERIODO,2)+'-01' AS DATA_PREVISAO,
	O.QUANTIDADE  AS VL_VOLUME,
	O.QUANTIDADE AS VL_VOLUME_ORIGINAL
FROM 
	PROJETO_BI_REVITALIZA.DBO.FATO_ORCAMENTO O 
WHERE 
	O.QUANTIDADE IS NOT NULL AND O.QUANTIDADE > 0 AND O.CENARIO = 'CENÁRIO 1' AND O.PERIODO >= '202402' AND O.VERSAO = 'ORÇADO' AND O.COD_CANAL <> 191 



----- TRATANDO BROKER -----------------------------------------------
DELETE FROM MPRICING.DBO.TB_PREVISAO_VENDA WHERE CD_ZONA = 191 AND DATA_PREVISAO >='2024-05-01'
DELETE FROM MPRICING.DBO.TB_PREVISAO_VENDA_PRODUTO WHERE CD_ZONA = 191 AND DATA_PREVISAO >='2024-05-01'

-- INSERINDO PREVISÃO PRODUTO
INSERT INTO TB_PREVISAO_VENDA_PRODUTO
SELECT
	O.COD_CANAL AS CD_ZONA, 
	CONVERT(VARCHAR(3),REPLICATE('0', 3 - LEN(O.COD_ESTABELECIMENTO)) + RTRIM(O.COD_ESTABELECIMENTO)) AS CD_ESTABELECIMENTO,
	O.COD_CLIENTE AS CD_CLIENTE, 
	O.COD_PRODUTO AS CD_PRODUTO,
	LEFT(O.PERIODO,4)+'-'+RIGHT(O.PERIODO,2)+'-01' AS DATA_PREVISAO,
	O.QUANTIDADE  AS VL_VOLUME
FROM 
	PROJETO_BI_REVITALIZA.DBO.FATO_ORCAMENTO O 
WHERE 
	O.QUANTIDADE IS NOT NULL AND O.QUANTIDADE > 0 AND O.CENARIO = 'CENÁRIO 1' AND O.PERIODO >= '202405' AND O.VERSAO = 'ORÇADO' AND O.COD_CANAL = 191 

-- INSERINDO PREVISÃO EV
INSERT INTO TB_PREVISAO_VENDA
SELECT
	O.COD_CANAL AS CD_ZONA, 
	CONVERT(VARCHAR(3),REPLICATE('0', 3 - LEN(O.COD_ESTABELECIMENTO)) + RTRIM(O.COD_ESTABELECIMENTO)) AS CD_ESTABELECIMENTO,
	O.COD_CLIENTE AS CD_CLIENTE, 
	O.COD_PRODUTO AS CD_PRODUTO,
	LEFT(O.PERIODO,4)+'-'+RIGHT(O.PERIODO,2)+'-01' AS DATA_PREVISAO,
	O.QUANTIDADE  AS VL_VOLUME,
	O.QUANTIDADE AS VL_VOLUME_ORIGINAL
FROM 
	PROJETO_BI_REVITALIZA.DBO.FATO_ORCAMENTO O 
WHERE 
	O.QUANTIDADE IS NOT NULL AND O.QUANTIDADE > 0 AND O.CENARIO = 'CENÁRIO 1' AND O.PERIODO >= '202405' AND O.VERSAO = 'ORÇADO' AND O.COD_CANAL = 191 

